name = "exercise-api"
main = "src/index.ts"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1

[[kv_namespaces]]
binding = "KV"
id = "7633b7ed94d24c3fa21d475e92957eae"
preview_id = "7633b7ed94d24c3fa21d475e92957eae"
remote = true
